### ISSUE TITLE
ترجمة رخصة غنو الإصدار 3

### ISSUE THREAD

**Issue by geekdiop** [aosus/arabic-tech-dictionary#14]
فتحت هذه "القضية" لأتمكن من ابداء رأيي في الرخصة.بم أتها باللغة الأنجلزية، كنت أرى لو أنشأتم ملفا جديدا بالعربية وإضافة هذه الترجمة عليه (ليست رسمية) ليستفيد منها الأخرون ومعرفة شروط هذا الإصدار من الرخصة.
هذا هو رابط العمل

" https://fairsultan.files.wordpress.com/2013/03/gpl-3-0-ar1.pdf "

**Comment by FarisZR** [comment]
مشكله الترجمة انها ليست مختبره قانونيا

وايضا ان موقع github لا يعترف بها

عكس حاليا يظهر GPL-3 بشكل واضح

**Comment by geekdiop** [comment]
شكرا على التوضيح.
