### ISSUE TITLE
لماذا اتجاه المحتوى من اليسار الى اليمين ltr ؟

### ISSUE THREAD

**Issue by ibeladi-mrsool** [aosus/arabic-tech-dictionary#29]
من المفترض ان تكون ان تكون الكلمة في اليمين والمعنى في اليسار, لكن الحاصل هو العنوان بالترتيب الصحيح لكن محتوى الجدول عكس ذلك
![image](https://user-images.githubusercontent.com/11488356/166111268-f3fb7a70-1e15-45c9-9ddf-ba8c17338357.png)

يمكنني العمل عليها في حال الموافقة على ذلك, او توضيح سبب عملها بهذه الطريقة

**Comment by FarisZR** [comment]
شكرا لك على الملاحظة.
سنكون شاكرين لك اذا عمل عليها.
