### ISSUE TITLE
كلمات يجب تغيير ترجمتها

### ISSUE THREAD

**Issue by fariszr** [aosus/arabic-tech-dictionary#5]
## قائمة من الترجمات التي يجب تغييرها 

<div dir="rtl">

![image](https://user-images.githubusercontent.com/35614734/131251604-610f63eb-beb0-4987-8727-95aa7faaf5b7.png)
![image](https://user-images.githubusercontent.com/35614734/131251609-b764a6b2-38bf-4efe-be5a-4864ff3bb319.png)
![image](https://user-images.githubusercontent.com/35614734/131251635-c9db6c05-c30e-44ea-927e-a454c5cbd0b1.png)
![image](https://user-images.githubusercontent.com/35614734/131251637-bd04e632-a46f-4668-b297-5282a53cf006.png)

اذا هناك اي كلمة اخرى رد على المشكلة هنا
</div>

**Comment by ots25** [comment]
Animation تحريكة

**Comment by ots25** [comment]
Anti-aliasing مضاد التسنن

**Comment by ots25** [comment]
> Animation تحريكة

 الرسم المتحرك، ج الرسوم متحركة
![Screenshot_20210829_153057.jpg](https://user-images.githubusercontent.com/89610703/131254404-754dc1df-f2d5-4fca-bfd0-61c492983c0f.jpg)
![Screenshot_20210829_152927.jpg](https://user-images.githubusercontent.com/89610703/131254411-2bfefcc4-26f8-4870-9da4-4e7b6e50a4a4.jpg)
* نظام أندوريد 10

**Comment by ots25** [comment]
> Animation تحريكة



> Anti-aliasing مضاد التسنن

التنعيم أو مضاد التعرُّج

**Comment by fariszr** [comment]
لا تغلق المشكله لانه تجميع لكل الكلمات

**Comment by fariszr** [comment]
> > Animation تحريكة
> 
> الرسم المتحرك، ج الرسوم متحركة
> ![Screenshot_20210829_153057.jpg](https://user-images.githubusercontent.com/89610703/131254404-754dc1df-f2d5-4fca-bfd0-61c492983c0f.jpg)
> ![Screenshot_20210829_152927.jpg](https://user-images.githubusercontent.com/89610703/131254411-2bfefcc4-26f8-4870-9da4-4e7b6e50a4a4.jpg)
> 
>     * نظام أندوريد 10

افتح pr
عشان هذا التعديل والمناقشة فيه

**Comment by fariszr** [comment]
كلمات اخرى
![image](https://user-images.githubusercontent.com/35614734/131257477-60e8feb7-c783-4be7-949c-ebcb25ff8be5.png)
![image](https://user-images.githubusercontent.com/35614734/131257506-acee45c9-e2a8-4044-8668-69a4569269a5.png)
![image](https://user-images.githubusercontent.com/35614734/131257652-654d0e50-4cd5-481a-9617-965c0bcda853.png)


ايضا اليس افضل ترجمتها الى نواه مصغرة ؟
![image](https://user-images.githubusercontent.com/35614734/131257550-dd7186f7-c320-4787-a140-15620de3be15.png)

**Comment by ots25** [comment]
![Screenshot_20210829_172557.jpg](https://user-images.githubusercontent.com/89610703/131257843-c79712df-f580-484f-868f-6722c785eaad.jpg)
هنا ترجمة Bell إلى جرس وهي كذلك، أما في المثال أعلاه ترجمت إلى ناقوس

**Comment by usama-makhzoum** [comment]
أيضا:


إجهاض
تأويل مجرد
تأويل مجرد
مركِّم
تسيير الممتلكات
بصمة منطوقة
إشهاد
خُطاطة
الخلوص
محرف الخلوص
محاكاة التلدين

**Comment by muabz** [comment]
بالنسبة ل
Tar archive
فأظن أن المعنى واضح وهو أرشيف بامتداد
tar

كلمة
archive
تعريبها هو أرشيف كما أقره كثير من اللغويين أما محفوظة فهي صعبة الفهم

كلمة
tar
اختصارا ل
tape archive
تبقى كما هي لأنها امتداد ملف



وعليه أقترح ترجمة
tar archive

ب

أرشيف
tar

تعمدت الانتقال من سطر ﻵخر لأن جيتهاب لا يدعم الكتابة من اليمين

**Comment by fariszr** [comment]
اتفق معك.
أرشيف
Tar

-------- Original Message --------

**Comment by muabz** [comment]
> > Anti-aliasing مضاد التسنن
> 
> التنعيم أو مضاد التعرُّج
> ![IMG_20210829_155134_443.jpg](https://user-images.githubusercontent.com/89610703/131254756-c93637d4-11e5-47dc-a32c-b8888b8cc4f3.jpg)
> ![IMG_20210829_155139_024.jpg](https://user-images.githubusercontent.com/89610703/131254763-7e3e9316-af2f-45ee-8a76-223af7986c92.jpg)
> 
> * المصدر: جنوم 40

أرى أن كلمة التنعيم يُفهم منها إما جعل ملمس الشيء ناعما أو جعل الحياة طيبة أو مرفهة.
وأرى أن حواف النوافذ المبكسلة لا ينطبق عليها معنى كلمة تنعيم.

أما التعرج فهو الميلان والانعطاف وهو ما لا أراه منطبقا على شكل حواف النوافذ

لذلك أقترح ترجمة
Anti-aliasing

ب
إزالة التَسَنُّن

**Comment by muabz** [comment]
> ## قائمة من الترجمات التي يجب تغييرها
> ![image](https://user-images.githubusercontent.com/35614734/131251604-610f63eb-beb0-4987-8727-95aa7faaf5b7.png)
> ![image](https://user-images.githubusercontent.com/35614734/131251609-b764a6b2-38bf-4efe-be5a-4864ff3bb319.png)
> ![image](https://user-images.githubusercontent.com/35614734/131251635-c9db6c05-c30e-44ea-927e-a454c5cbd0b1.png)
> ![image](https://user-images.githubusercontent.com/35614734/131251637-bd04e632-a46f-4668-b297-5282a53cf006.png)
> 
> اذا هناك اي كلمة اخرى رد على المشكلة هنا

أرى ترجمة كلمة
technique
ب

تِقْنِيَّة

مع التأكيد على تسكين القاف حتى لا تنطق بصفة خاطئة مثلما هو رائج أنها تِقَنِيَّة بفتح القاف
والمقصود هنا هو طريقة أو كيفية عمل الشيء

أما كلمة
Technology
فأرى ترجمتها ب

تكنولوجيا

كلمة تقانة لها نفس معنى كلمة تكنولوجيا وهو علم الصناعة بشتى مجالاتها لكني أرى أن تقانة قد تكون غير مفهومة للمستخدم
لذلك اقترحت كلمة تكنولوجيا وهو اسم معرب أقره اللغويون في العصر الحديث لأنه عُرِّب كما عُرَِبت كلمات جغرافيا وجيولوجيا وديموغرافيا وهي أيضا علوم تماما مثل التكنولوجيا


المصدر معجم اللغة العرية المعاصرة
![photo_2021-09-04_11-35-02](https://user-images.githubusercontent.com/89611096/132091662-f2869314-80ad-44d7-ad9d-3bedba2407aa.jpg)

**Comment by fariszr** [comment]
تم نقل النقاش الى قسم معجم أسس
بسبب عدم دعم العربية في GITHUB

https://aosus.org/t/topic/2113
