### ISSUE TITLE
تصحيح قاموس عيون العرب كلمة بكلمة

### ISSUE THREAD

**Issue by ghost** [aosus/arabic-tech-dictionary#7]
أنشأت هذا الموضوع لتصحيح ما نجده يحتاج لذلك في قاموس عيون العرب وأيضا المصادقة على ما نوافق عليه من الترجمات
بحيث أتناول قاموس عيون العرب من الإنجليزية إلى العربية كلمة بكلمة حسب الترتيب الألفبائي
نصادق على الترجمة التي نراها صحيحة ونصحح الترجمة التي نراها خاطئة

**Comment by muabz** [comment]
![1111111111111111](https://user-images.githubusercontent.com/89611096/132127754-5846820d-6ef3-4306-88d7-ff610a9d9275.png)


كلمة #0001

Abort

تُرجمت بكلمة إجهاض

كلمة إجها	ض لغويا تحتمل المعنى الطبي كما تحتمل معنى الإفساد أو الإزالة أو التنحية
لما كان المعنى الرائج والغالب حاليا لكلمة إجهاض هو إسقاط الحمل وبسبب صعوبة فهمه تقنيا بالمعنى المناسب فأقترح تعديله

اقتراحي هو 

تغيير كلمة إجهاض لكلمة إحباط

إحباط تعني لغويا إبطال وإعاقة وإيقاف الأمر والحيلولة دون اكتمال تنفيذه أو إفشاله

قول أحدهم جملة أشعر بالإحباط قاصدا بها شعوره بالحزن واليأس إنما أصل شعوره هذا هو الفشل في أمر ما وهو أصل معنى كلمة إحباط

أرى كلمة إحباط أقرب لغويا وتقنيا من كلمتي إيقاف أو إلغاء اللتان تملكان ترجمات إنجليزية أخرى و أقرب أيضا من كلمة تثبيط التي تعني التعطيل أو الإيقاف المؤقت وليس التام


ملخص الاقتراح

ترجمة 
Abort
لكلمة إحباط بدل إجهاض

**Comment by fariszr** [comment]
تم نقل الموضوع الى
https://aosus.org/t/topic/2114
